### ISSUE TITLE
Unexpected end of file at zlib._handle.onerror

### ISSUE THREAD

**Issue by Feverqwe** [serviejs/popsicle#115]
Hello! I use this code and url response gzip.
```javascript
const request = popsicle.request({
  method: 'GET',
  url: url,
  transport: popsicle.createTransport({
    type: 'stream'
  })
});
return request.then(function (res) {
  res.body.on('error', err => {});

  if (res.status !== 200) {
    request.abort();
    throw new Error('Bad status');
  }

  ...
});
```

If status will not 200 and I don't add after then this code:
```javascript
res.body.on('error', err => {});
```
Will throw zlib error as Uncaught exception without stack. It is ok?

**Comment by Feverqwe** [comment]
I don't know, how to do better. But just need know about this exception. Maybe need write about it in documentation.

**Comment by blakeembrey** [comment]
I believe this has been improved with the new API design based on `servie`.
