### ISSUE TITLE
Consider taking on @types?

### ISSUE THREAD

**Issue by unional** [serviejs/popsicle#97]
Since [redirect](https://github.com/Microsoft/types-publisher/issues/4) does not seem to be happening anytime soon, will you consider moving to use `@types` and remove `typings`?

I'm currently trying to do a wrapper on `popsicle` to add in addition code needed for our product. That means I have to either re-export `popsicle` typings (i.e. need to use `typings` in that library and the consumer of that library) or replicate the typings I needed.

If you think we should still wait for redirect, I'm fine with that too, and will just do the second way instead.

**Comment by blakeembrey** [comment]
Sure, I could do that. I think the biggest stoppest when I looked was that the types literally didn't exist in DefinitelyTyped or were wrong. There's also the issue of https://github.com/Microsoft/TypeScript/issues/7753, but it might just have to be something I deal with (the types will be incorrect somewhat in the browser).
